development:
  adapter: postgresql
  encoding: unicode
  database: test_development
  host: localhost
  pool: 5
  username: test
  password: 113ec0224

test:
  adapter: postgresql
  encoding: unicode
  database: zerocode_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: zerocode_production
  pool: 5
  username: 
  password: